export type {
  PracticeMode,
  AppConfig,
  ReferenceDisplayVideo,
  RandomTask,
  SegmentTiming,
  Point,
  FramePoints,
  FrameData,
  OverlayPayload,
  PlaybackPayload,
  JointStatus,
  MainError,
  FeedbackBlock,
  Decision,
  ReferenceBlock,
  VisualizationPayload,
  BankMatch,
  AnalyzeResponse,
  AnalyzeAttemptParams
} from "./types";

export { 
  ensureBaseUrl, 
  registerUser, 
  loginUser, 
  getCurrentUser, 
  getReviewWords, 
  markWordViewed, 
  updateResumeState,
  getParentDashboard,
  getSchoolDashboard,
  getVocabularyDetail,
  updateProfile,
  searchLearners,
  requestParentLink,
  requestSchoolLink,
  getPendingLinks,
  approveParentLink,
  rejectParentLink,
  approveSchoolLink,
  rejectSchoolLink,
  getLearnerDashboard,
  getMyProgress,
  createChild,
  createStudent,
  refreshAIRecommendation,
  getWordBank,
  getCustomPackages,
  createCustomPackage,
  deleteCustomPackage,
  assignCustomPackage,
  getAssignedPackages,
} from "./client";
export type { BankWordItem, CustomPackage as CustomPackageData } from "./client";
export { loadAppConfig, loadCurriculum } from "./endpoints/app";
export { createRandomTask, analyzeAttempt } from "./endpoints/practice";
