"""add index practice_attempts learner_created

Revision ID: 86d6b8d0423f
Revises: 0c1b3b2dff58
Create Date: 2026-05-27 09:21:11.053122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d6b8d0423f'
down_revision: Union[str, Sequence[str], None] = '0c1b3b2dff58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_practice_attempts_learner_created', 'practice_attempts', ['learner_user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_practice_attempts_learner_created', table_name='practice_attempts')
    # ### end Alembic commands ###
