"""Initial migrations

Revision ID: 8e86487f4bc7
Revises: 
Create Date: 2026-05-23 14:15:51.923979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e86487f4bc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_config_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('topics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('learner_badges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('badge_id', sa.Uuid(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_user_id', 'badge_id', name='uq_learner_badge')
    )
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('learning_streak', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('resume_state_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('learner_topic_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=False),
    sa.Column('completed_words', sa.Integer(), nullable=False),
    sa.Column('checkpoint5_passed', sa.Boolean(), nullable=False),
    sa.Column('practice2_final_passed', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('last_word_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_user_id', 'topic_id', name='uq_learner_topic')
    )
    op.create_table('parent_learner_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_user_id', sa.Uuid(), nullable=False),
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_user_id', 'learner_user_id', name='uq_parent_learner')
    )
    op.create_table('parent_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('school_learner_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_user_id', sa.Uuid(), nullable=False),
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('student_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_user_id', 'learner_user_id', name='uq_school_learner')
    )
    op.create_table('school_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('school_name', sa.String(length=150), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('streak_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_user_id', 'date', name='uq_learner_streak_date')
    )
    op.create_table('words',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gloss', sa.String(length=100), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('checkpoint_group', sa.Integer(), nullable=False),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.Column('reference_video_url', sa.String(length=255), nullable=True),
    sa.Column('reference_playback_url', sa.String(length=255), nullable=True),
    sa.Column('reference_start_ms', sa.Integer(), nullable=True),
    sa.Column('reference_end_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_gloss'), 'words', ['gloss'], unique=True)
    op.create_table('learner_word_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('studied', sa.Boolean(), nullable=False),
    sa.Column('practice1_attempt_count', sa.Integer(), nullable=False),
    sa.Column('best_practice1_score', sa.Float(), nullable=True),
    sa.Column('last_practice1_score', sa.Float(), nullable=True),
    sa.Column('accepted_once', sa.Boolean(), nullable=False),
    sa.Column('failed_attempt_count', sa.Integer(), nullable=False),
    sa.Column('correct_attempt_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_user_id', 'word_id', name='uq_learner_word')
    )
    op.create_table('practice_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=True),
    sa.Column('word_id', sa.Uuid(), nullable=True),
    sa.Column('practice_mode', sa.String(length=20), nullable=False),
    sa.Column('target_gloss', sa.String(length=100), nullable=False),
    sa.Column('lesson_glosses_json', sa.JSON(), nullable=False),
    sa.Column('uploaded_video_path', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('wrong_word_detected', sa.Boolean(), nullable=False),
    sa.Column('predicted_wrong_gloss', sa.String(length=100), nullable=True),
    sa.Column('target_rank', sa.Integer(), nullable=True),
    sa.Column('segment_start_ms', sa.Integer(), nullable=True),
    sa.Column('segment_end_ms', sa.Integer(), nullable=True),
    sa.Column('frame_stride', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_attempt_feedback',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('overall_text', sa.Text(), nullable=True),
    sa.Column('main_errors_json', sa.JSON(), nullable=True),
    sa.Column('decision_json', sa.JSON(), nullable=True),
    sa.Column('top_matches_json', sa.JSON(), nullable=True),
    sa.Column('overlay_meta_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['practice_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('practice_attempt_metrics',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('valid_fraction', sa.Float(), nullable=False),
    sa.Column('pose_sequence_length', sa.Integer(), nullable=False),
    sa.Column('analysis_duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['practice_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_attempt_metrics')
    op.drop_table('practice_attempt_feedback')
    op.drop_table('practice_attempts')
    op.drop_table('learner_word_progress')
    op.drop_index(op.f('ix_words_gloss'), table_name='words')
    op.drop_table('words')
    op.drop_table('streak_logs')
    op.drop_table('school_profiles')
    op.drop_table('school_learner_links')
    op.drop_table('parent_profiles')
    op.drop_table('parent_learner_links')
    op.drop_table('learner_topic_progress')
    op.drop_table('learner_profiles')
    op.drop_table('learner_badges')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('badges')
    # ### end Alembic commands ###
