"""add_mascot_shop

Revision ID: aa6a66213a45
Revises: f6a4d2c8b91a
Create Date: 2026-05-26 19:18:20.571355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6a66213a45'
down_revision: Union[str, Sequence[str], None] = 'f6a4d2c8b91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascot_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('preview_filename', sa.String(length=100), nullable=False),
    sa.Column('mascot_filename', sa.String(length=100), nullable=False),
    sa.Column('xp_cost', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('learner_mascot_config',
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('active_item_key', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_item_key'], ['mascot_items.item_key'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_user_id')
    )
    op.create_table('learner_mascot_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_user_id', sa.Uuid(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_key'], ['mascot_items.item_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_user_id', 'item_key', name='uq_learner_mascot_item')
    )
    # Seed initial mascot shop items
    mascot_items_table = sa.table(
        "mascot_items",
        sa.column("item_key", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("preview_filename", sa.String),
        sa.column("mascot_filename", sa.String),
        sa.column("xp_cost", sa.Integer),
        sa.column("is_available", sa.Boolean),
    )
    op.bulk_insert(mascot_items_table, [
        {
            "item_key": "cape",
            "name": "Áo choàng",
            "description": "Khoác áo choàng cho linh vật của bạn!",
            "preview_filename": "cape.png",
            "mascot_filename": "mascot_cape.png",
            "xp_cost": 100,
            "is_available": True,
        },
        {
            "item_key": "glasses",
            "name": "Kính mắt",
            "description": "Trông thông minh hơn với cặp kính!",
            "preview_filename": "mascot_glasses.png",
            "mascot_filename": "mascot_glasses.png",
            "xp_cost": 80,
            "is_available": True,
        },
        {
            "item_key": "hat",
            "name": "Mũ",
            "description": "Đội mũ thật ngầu cho linh vật!",
            "preview_filename": "hat.png",
            "mascot_filename": "mascot_hat.png",
            "xp_cost": 120,
            "is_available": True,
        },
        {
            "item_key": "mascot_cape",
            "name": "Mascot Áo choàng đặc biệt",
            "description": "Phiên bản đặc biệt của linh vật với áo choàng huyền thoại!",
            "preview_filename": "mascot_cape.png",
            "mascot_filename": "mascot_cape.png",
            "xp_cost": 200,
            "is_available": True,
        },
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learner_mascot_items')
    op.drop_table('learner_mascot_config')
    op.drop_table('mascot_items')
    # ### end Alembic commands ###
