"""add_custom_package_assignments

Revision ID: de56b8151b77
Revises: edc37d0d3598
Create Date: 2026-05-25 23:26:32.579656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de56b8151b77'
down_revision: Union[str, Sequence[str], None] = 'edc37d0d3598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_packages', sa.Column('assigned_class_name', sa.String(length=50), nullable=True))
    op.add_column('custom_packages', sa.Column('assigned_student_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_packages', 'assigned_student_ids')
    op.drop_column('custom_packages', 'assigned_class_name')
    # ### end Alembic commands ###
